version: '3'

networks:
  middleware-network:
    driver: bridge

volumes:
  middleware_data: {}

services:
  xxl-job:
    image: xuxueli/xxl-job-admin:2.2.0
    container_name: xxljob
    ports:
    - 8089:8080
    environment:
      PARAMS: "--spring.datasource.url=jdbc:mysql://120.46.151.254:13306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai  --spring.datasource.username=xxljob  --spring.datasource.password=xxljob"
    volumes:
    - ./data/logs/:/data/applogs/xxl-job/
    networks:
      middleware-network:
        aliases:
          - xxljob