version: '3'

networks:
  middleware-network:
    driver: bridge

volumes:
  middleware_data: {}

services:

  rabbitmq:
    image: rabbitmq:3.7.15-management
    container_name: rabbitmq
    volumes:
      - ./data/rabbitmq/data:/var/lib/rabbitmq #数据文件挂载
      - ./data/rabbitmq/log:/var/log/rabbitmq #日志文件挂载
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      middleware-network:
        aliases:
          - rabbitmq