global:
  scrape_interval:     15s

scrape_configs:
- job_name: "prometheus"
  scrape_interval: 5s
  static_configs:
  - targets: ["192.168.10.214:9090"]

- job_name: "node"
  static_configs:
    - targets: ["192.168.10.214:9100"]

