version: '3'

networks:
  middleware-network:
    driver: bridge

volumes:
  middleware_data: {}

services:
  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins
    ports:
    - 8181:8080
    - 8182:50000
    volumes:
    - ./jenkins_home/:/var/jenkins_home
    - /etc/localtime:/etc/localtime #让容器使用和服务器同样的时间设置
    networks:
      middleware-network:
        aliases:
          - jenkins