version: '3'

networks:
  middleware-network:
    driver: bridge

volumes:
  middleware_data: {}

services:

  portainer:
    container_name: portainer
    image: portainer/portainer
    volumes:
      - ./data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    networks:
      middleware-network:
        aliases:
          - portainer