version: '3.0'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9010:9010"
      - "9011:9000"
    restart: always
    command: server /data --console-address ":9010"
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: minioadmin
    logging:
      options:
        max-size: "50M" # 最大文件上传限制
        max-file: "10"
      driver: json-file
    volumes:
      - ./data/minio/data:/data # 映射文件路径
