version: '3'

networks:
  middleware-network:
    driver: bridge

volumes:
  middleware_data: {}

services:

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    volumes:
      - ./data/kafka-logs:/kafka #数据文件挂载
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://120.46.151.254:9092 #120.46.151.254 部署机器IP
      KAFKA_CREATE_TOPICS: "kafeidou:2:0"   #kafka启动后初始化一个有2个partition(分区)0个副本名叫kafeidou的topic
      KAFKA_ZOOKEEPER_CONNECT: 120.46.151.254:2181 #zookeeper部署机器IP 120.46.151.254
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    networks:
      middleware-network:
        aliases:
          - kafka


  kafka-map:
    image: dushixiang/kafka-map:latest
    container_name: kafka-map
    ports:
    - 9093:8080
    volumes:
      - ./data/kafka-map:/usr/local/kafka-map/data
    environment:
      DEFAULT_USERNAME: admin
      DEFAULT_PASSWORD: admin